<?xml version ='1.0' encoding ='UTF-8' ?>
<definitions
        name='Stock'
     targetNamespace='http://lst02.camco/soap/factoriya'
     xmlns:tns='http://lst02.camco/soap/factoriya'
        xmlns:xsd='http://www.w3.org/2001/XMLSchema'
     xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/'
     xmlns:soapenc='http://schemas.xmlsoap.org/soap/encoding/'
     xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'
     xmlns='http://schemas.xmlsoap.org/wsdl/'
>

    <message name='getStockRequest'>
        <part name='shelf_name' type='xsd:string'/>
    </message>
    <message name='getStockResponse'>
        <part name='Result' type='xsd:integer'/>
    </message>

    <portType name='StockPortType'>
        <operation name='getStock'>
            <input message='tns:getStockRequest'/>
            <output message='tns:getStockResponse'/>
        </operation>
    </portType>

    <binding name='StockBinding' type='tns:StockPortType'>
        <soap:binding style='rpc' transport='http://schemas.xmlsoap.org/soap/http'/> <!-- transport - зависит от выбранной версии протокола в данном случае soap 1.1 -->
        <operation name='getStock' />
    </binding>

    <service name='StockService'>
        <port name='StockPort' binding='StockBinding'>
            <soap:address location='http://lst02.camco/soap/factoriya/server.php'/>
        </port>
    </service>
</definitions>